version: '3'
services:
  backend:
    image: alexapplemanzer/applesite:v1
    environment:
      - NODE_ENV=production
    build: 
      context: ./applesite-backend
      dockerfile: ./Dockerfile
    command: node ./src/app.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    image: alexapplemanzer/applesitefrontend:v1
    build: 
      context: ./applesite-frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  mongo:
    image: mongo:v1
    ports:
      - "27017:27017"
  
