version: '3'
services:
  backend:
    image: applesite-backend
    environment:
      - NODE_ENV=production
    build: 
      context: ./applesite-backend
      dockerfile: ./Dockerfile
    command: node ./src/app.js
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  frontend:
    image: applesite-frontend
    build: 
      context: ./applesite-frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  
